Repository VODGroup/VoiceOverDesigner, pull requests merged in 2022-08, with the labels that each got.

#73 Add tests and fix updating of views
  Document/Sources/Document/Documents/VODesignDocument+AppKit.swift
  Document/Sources/Document/Drawing/DrawingController.swift
  Document/Sources/Document/Drawing/DrawingView.swift
  VoiceOver Designer.xcodeproj/project.pbxproj
  VoiceOver Designer/AppDelegate.swift
  VoiceOver Designer/Base.lproj/Main.storyboard
  VoiceOver Designer/Features/Sources/Editor/EditorPresenter.swift
  VoiceOver Designer/Features/Sources/Settings/SettingsViewController.swift
  VoiceOver Designer/Features/Sources/Settings/Value/A11yValueViewController.swift
  VoiceOver Designer/Features/Tests/EditorTests/Base/EditorAfterDidLoadTests.swift
  VoiceOver Designer/Features/Tests/EditorTests/Base/EditorTests.swift
  VoiceOver Designer/Features/Tests/EditorTests/Doubles/DocumentFake.swift
  VoiceOver Designer/Features/Tests/EditorTests/Doubles/EditorDelegateMock.swift
  VoiceOver Designer/Features/Tests/EditorTests/Doubles/EmptyViewController.swift
  VoiceOver Designer/Features/Tests/EditorTests/Doubles/RouterMock.swift
  VoiceOver Designer/Features/Tests/EditorTests/EditorPresenterTests.swift
  VoiceOver Designer/Features/Tests/EditorTests/EditorUpdatingTests.swift
  VoiceOver Designer/Features/Tests/EditorTests/NewDrawingTests.swift
  VoiceOver Designer/Features/Tests/EditorTests/RoutingTests.swift
  VoiceOver Designer/Features/Tests/EditorTests/TranslatingTests.swift
  VoiceOver Designer/Router.swift
  VoiceOver Designer/VODocumentController.swift
  VoiceOver Designer/WindowController.swift
Labels: enhancement, Tests

#69 59 copy action when move element with pressed alt
  Document/Sources/Document/Drawing/Actions/Action.swift
  Document/Sources/Document/Drawing/Actions/ClickAction.swift
  Document/Sources/Document/Drawing/Actions/CopyAction.swift
  Document/Sources/Document/Drawing/Actions/CopyAndTranslateAction.swift
  Document/Sources/Document/Drawing/Actions/NewControlAction.swift
  Document/Sources/Document/Drawing/Actions/TranslateAction.swift
  Document/Sources/Document/Drawing/CopyCommand/CopyModifierCommand.swift
  Document/Sources/Document/Drawing/CopyCommand/CopyModifierProtocol.swift
  Document/Sources/Document/Drawing/CopyCommand/ManualCopyCommand.swift
  Document/Sources/Document/Drawing/DrawingController.swift
  Document/Sources/Document/Drawing/DrawingView.swift
  Document/Sources/Document/Models/A11yControl.swift
  Document/Sources/Document/Models/A11yDescription.swift
  VoiceOver Designer.xcworkspace/contents.xcworkspacedata
  VoiceOver Designer/Features/Sources/Editor/EditorPresenter.swift
  VoiceOver Designer/Features/Sources/Editor/EditorView.swift
  VoiceOver Designer/Features/Tests/EditorTests/Doubles/DocumentFake.swift
  VoiceOver Designer/Features/Tests/EditorTests/TranslatingTests.swift
  VoiceOver Preview/PreviewFeatures/Sources/DesignPreview/VODesignPreviewView.swift
  VoiceOver Preview/VoiceOver Preview.xcodeproj/project.pbxproj
Labels: enhancement

#84 Add empty contoller instead of sidebar
  Document/Sources/Document/Models/A11yDescription.swift
  VoiceOver Designer/Features/Sources/Settings/SettingsStateViewController.storyboard
  VoiceOver Designer/Features/Sources/Settings/SettingsStateViewController.swift
  VoiceOver Designer/Features/Sources/Settings/StateViewController.swift
  VoiceOver Designer/Features/Sources/Settings/States/Control/Settings.storyboard
  VoiceOver Designer/Features/Sources/Settings/States/Control/SettingsPresenter.swift
  VoiceOver Designer/Features/Sources/Settings/States/Control/SettingsViewController.swift
  VoiceOver Designer/Features/Sources/Settings/States/Control/Value/A11yValueView.swift
  VoiceOver Designer/Features/Sources/Settings/States/Control/Value/A11yValueViewController.storyboard
  VoiceOver Designer/Features/Sources/Settings/States/Control/Value/A11yValueViewController.swift
  VoiceOver Designer/Features/Sources/Settings/States/Control/Value/AdjustableOptionView.swift
  VoiceOver Designer/Features/Sources/Settings/States/Empty/EmptyViewController.storyboard
  VoiceOver Designer/Features/Sources/Settings/States/Empty/EmptyViewController.swift
  VoiceOver Designer/Features/Tests/EditorTests/Base/EditorTests.swift
  VoiceOver Designer/Features/Tests/EditorTests/TranslatingTests.swift
  VoiceOver Designer/Router.swift
Labels: enhancement

#92 Enumerate all elements of adjustable control
  Document/Sources/Document/Models/A11yDescription.swift
  Document/Sources/Document/Models/AdjustableOptions.swift
  Document/Tests/DocumentTests/A11yDescriptionTests.swift
  Document/Tests/DocumentTests/AdjustableOptionsTests.swift
  VoiceOver Designer/Features/Sources/Editor/EditorView.swift
  VoiceOver Designer/Features/Sources/Settings/States/Control/Value/A11yValueView.swift
  VoiceOver Designer/Features/Sources/Settings/States/Control/Value/A11yValueViewController.storyboard
  VoiceOver Designer/Features/Sources/Settings/States/Control/Value/A11yValueViewController.swift
  VoiceOver Designer/Features/Sources/Settings/States/Control/Value/AdjustableOptionView.swift
  VoiceOver Designer/Features/Tests/SettingsTests/AdjustableViewControllerSnapshotTests.swift
  VoiceOver Designer/Features/Tests/SettingsTests/__Snapshots__/AdjustableViewControllerSnapshotTests/test_adjustable_noSamples.1.png
  VoiceOver Designer/Features/Tests/SettingsTests/__Snapshots__/AdjustableViewControllerSnapshotTests/test_adjustable_withSamples.1.png
  VoiceOver Designer/Features/Tests/SettingsTests/__Snapshots__/AdjustableViewControllerSnapshotTests/test_empty.1.png
  VoiceOver Designer/Features/Tests/SettingsTests/__Snapshots__/AdjustableViewControllerSnapshotTests/test_notAdjustable_withSamples.1.png
  VoiceOver Designer/Features/Tests/SettingsTests/__Snapshots__/AdjustableViewControllerSnapshotTests/test_value_notAdjustable.1.png
Labels: enhancement

#93 VOdocument migration
  Document/Sources/Document/Models/A11yCustomActions.swift
  Document/Sources/Document/Models/A11yDescription.swift
  Document/Sources/Document/Models/AdjustableOptions.swift
  Document/Sources/Document/Models/Decadable/DecodableDefault+CustomActions.swift
  Document/Sources/Document/Models/Decadable/DecodableDefault.swift
Labels: bug

#94 91 add localization to all texts and plural forms
  Document/Package.swift
  Document/Sources/Document/Assets/en.lproj/Localizable.strings
  Document/Sources/Document/Assets/ru.lproj/Localizable.strings
  Document/Sources/Document/Models/A11yDescription+Localization.swift
  Document/Sources/Document/Models/A11yDescription.swift
  Document/Sources/Document/Models/AdjustableOptions+Localization.swift
  Document/Sources/Document/Models/AdjustableOptions.swift
  Document/Tests/DocumentTests/A11yDescription+TestMake.swift
  Document/Tests/DocumentTests/A11yDescriptionTests.swift
Labels: bug

#97 Cancel drawing operation with Esc
  Document/Sources/Document/Drawing/Actions/Action.swift
  Document/Sources/Document/Drawing/Actions/ClickAction.swift
  Document/Sources/Document/Drawing/Actions/CopyAction.swift
  Document/Sources/Document/Drawing/Actions/CopyAndTranslateAction.swift
  Document/Sources/Document/Drawing/Actions/NewControlAction.swift
  Document/Sources/Document/Drawing/Actions/ResizeAction.swift
  Document/Sources/Document/Drawing/Actions/TranslateAction.swift
  Document/Sources/Document/Drawing/DrawingController.swift
  Document/Sources/Document/Drawing/DrawingView.swift
  Document/Sources/Document/Drawing/EscCancelAction/EmptyEscModifierAction.swift
  Document/Sources/Document/Drawing/EscCancelAction/EscModifierAction.swift
  Document/Sources/Document/Drawing/EscCancelAction/EscModifierActionCommand.swift
  VoiceOver Designer/Features/Sources/Editor/EditorView.swift
  VoiceOver Designer/Features/Tests/EditorTests/CancellingActionsTests.swift
Labels: enhancement

#96 Toolbar redesign
  Document/Sources/Document/Assets/en.lproj/Localizable.strings
  Document/Sources/Document/Drawing/DrawingView.swift
  Document/Sources/Document/Models/A11yControl.swift
  Document/Sources/Document/Models/A11yDescription+Localization.swift
  VoiceOver Designer.xcodeproj/project.pbxproj
  VoiceOver Designer/Features/Sources/Editor/Editor.storyboard
  VoiceOver Designer/Features/Sources/Editor/EditorPresenter.swift
  VoiceOver Designer/Features/Sources/Editor/EditorView.swift
  VoiceOver Designer/Features/Sources/Editor/EditorViewController.swift
  VoiceOver Designer/Features/Sources/Settings/States/Control/Settings.storyboard
  VoiceOver Designer/Features/Sources/Settings/States/Control/SettingsViewController.swift
  VoiceOver Designer/Features/Sources/Settings/States/Parts/CustomActions/CustomActionOptionView.swift
  VoiceOver Designer/Features/Sources/Settings/States/Parts/CustomActions/CustomActionsView.swift
  VoiceOver Designer/Features/Sources/Settings/States/Parts/CustomActions/CustomActionsViewController.storyboard
  VoiceOver Designer/Features/Sources/Settings/States/Parts/CustomActions/CustomActionsViewController.swift
  VoiceOver Designer/Features/Sources/Settings/States/Parts/CustomDescription/CustomDescriptionViewController.storyboard
  VoiceOver Designer/Features/Sources/Settings/States/Parts/Settings.storyboard
  VoiceOver Designer/Features/Sources/Settings/States/Parts/SettingsPresenter.swift
  VoiceOver Designer/Features/Sources/Settings/States/Parts/SettingsView.swift
  VoiceOver Designer/Features/Sources/Settings/States/Parts/SettingsViewController.swift
  VoiceOver Designer/Features/Sources/Settings/States/Parts/Traits/TraitsViewController.storyboard
  VoiceOver Designer/Features/Sources/Settings/States/Parts/Traits/TraitsViewController.swift
  VoiceOver Designer/Features/Sources/Settings/States/Parts/Value/A11yValueView.swift
  VoiceOver Designer/Features/Sources/Settings/States/Parts/Value/A11yValueViewController.storyboard
  VoiceOver Designer/Features/Sources/Settings/States/Parts/Value/A11yValueViewController.swift
  VoiceOver Designer/Features/Sources/Settings/States/Parts/Value/AdjustableOptionView.swift
  VoiceOver Designer/Features/Sources/TextUI/TextRepresentationController.swift
  VoiceOver Designer/ProjectController+Toolbar.swift
  VoiceOver Designer/ProjectController.swift
  VoiceOver Designer/Router.swift
  VoiceOver Designer/WindowController.swift
  VoiceOver Preview/PreviewFeatures/Package.swift
Labels: enhancement

#100 Wrap text in left panel
  Document/Sources/Document/Models/A11yDescription+VoiceOver.swift
  Document/Sources/Document/Models/A11yDescription.swift
  Document/Sources/Document/Models/String+Markdown.swift
  Document/Tests/DocumentTests/A11yDescriptionTests.swift
  VoiceOver Designer/Features/Sources/Settings/States/Parts/SettingsView.swift
  VoiceOver Designer/Features/Sources/Settings/States/Parts/Traits/TraitsView.swift
  VoiceOver Designer/Features/Sources/Settings/States/Parts/Traits/TraitsViewController.storyboard
  VoiceOver Designer/Features/Sources/Settings/States/Parts/Traits/TraitsViewController.swift
  VoiceOver Designer/Features/Sources/Settings/States/Parts/Value/A11yValueView.swift
  VoiceOver Designer/Features/Sources/TextUI/TextRepresentationController+Dragging.swift
  VoiceOver Designer/Features/Sources/TextUI/TextRepresentationController.storyboard
  VoiceOver Designer/Features/Sources/TextUI/TextRepresentationController.swift
Labels: feature

#105 102 window managment
  Document/Sources/Document/Documents/VODocumentController.swift
  VoiceOver Designer.xcodeproj/project.pbxproj
  VoiceOver Designer/AppDelegate.swift
  VoiceOver Designer/Base.lproj/Main.storyboard
  VoiceOver Designer/Documents/VODesignDocument+Window.swift
  VoiceOver Designer/Documents/WindowManager.swift
  VoiceOver Designer/Features/Package.swift
  VoiceOver Designer/Features/Sources/Recent/Base.lproj/RecentWindowController.storyboard
  VoiceOver Designer/Features/Sources/Recent/Collection/RecentCellView.swift
  VoiceOver Designer/Features/Sources/Recent/Collection/RecentCollectionViewItem.swift
  VoiceOver Designer/Features/Sources/Recent/Recent.docc/Projects.md
  VoiceOver Designer/Features/Sources/Recent/RecentToolbar.swift
  VoiceOver Designer/Features/Sources/Recent/RecentView.swift
  VoiceOver Designer/Features/Sources/Recent/RecentViewController.storyboard
  VoiceOver Designer/Features/Sources/Recent/RecentViewController.swift
  VoiceOver Designer/Features/Sources/Recent/RecentWindowController.swift
  VoiceOver Designer/Features/Sources/Settings/States/Parts/Settings.storyboard
  VoiceOver Designer/Features/Sources/Settings/States/Parts/Value/A11yValueViewController.storyboard
  VoiceOver Designer/Features/Tests/RecentTests/ProjectCollectionViewItemTests.swift
  VoiceOver Designer/MainMenu.swift
  VoiceOver Designer/MainMenu.xib
  VoiceOver Designer/SingleDocument/ProjectController+Toolbar.swift
  VoiceOver Designer/SingleDocument/ProjectController.swift
  VoiceOver Designer/VODocumentController.swift
  VoiceOver Designer/WindowController.swift
  VoiceOver Designer/main.swift
  VoiceOver Preview/VoiceOver Preview.xcodeproj/xcshareddata/xcschemes/DesignerUITests.xcscheme
  VoiceOver-Designer-Info.plist
  VoiceOverDesignerUITests/AdjustableTest.swift
  VoiceOverDesignerUITests/Base/DesignerTests.swift
  VoiceOverDesignerUITests/Base/DocumentTests.swift
  VoiceOverDesignerUITests/DocumentFromFileTests.swift
  VoiceOverDesignerUITests/DrawingTests.swift
  VoiceOverDesignerUITests/PageObjects/ProjectWindow.swift
  VoiceOverDesignerUITests/PageObjects/ProjectsWindow.swift
  VoiceOverDesignerUITests/WindowTests.swift
Labels: feature

#108 Add placeholder label for empty document
  VoiceOver Designer/Features/Sources/CommonUI/DragNDropImageView.swift
  VoiceOver Designer/Features/Sources/Editor/Editor.storyboard
  VoiceOver Designer/Features/Sources/Editor/EditorView.swift
  VoiceOver Designer/Features/Sources/Editor/EditorViewController.swift
Labels: feature
